version: "3"
services:
  frontend:
    build:
      context: ./react-frontend
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./total-backend
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: O48h7DzohJtNNZyAmSbgWuCPhXjfXDSf
      POSTGRES_DB: easyvotes
